import './globals.css'

import type { Metadata } from 'next'
import Link from 'next/link'

import { Footer } from '@/components/Footer'
import { Providers } from '@/lib/provider'

export const metadata: Metadata = {
  title: 'Derma On Demand',
  description: 'Generated by Derma On Demand',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <Providers>
      <html lang="en">
        <body className="relative min-h-screen bg-[#EFF5F6]">
          <div className="flex h-screen flex-col">
            <nav>
              <div className="relative flex  h-[80px] w-full bg-white">
                <Link
                  href="/"
                  className="absolute left-10 self-center  text-primary"
                >
                  DermOnDemand
                </Link>
              </div>
            </nav>
            <main className="flex flex-1 items-center justify-center">
              {children}
            </main>
            <Footer />
          </div>
        </body>
      </html>
    </Providers>
  )
}
