import { Providers } from "@/lib/provider";
import "./globals.css";
import type { Metadata } from "next";
import { Jost } from "next/font/google";
import Link from "next/link";
import { Footer } from "@/components/Footer";

export const metadata: Metadata = {
  title: "Derma On Demand",
  description: "Generated by Derma On Demand",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Providers>
      <html lang="en">
        <body className={`min-h-screen bg-[#EFF5F6] relative`}>
          <div className="flex flex-col h-screen">
            <nav>
              <div className="bg-white w-full  h-[80px] relative flex">
                <Link
                  href="/"
                  className="text-primary absolute left-10  self-center"
                >
                  DermOnDemand
                </Link>
              </div>
            </nav>
            <main className="flex-1 flex justify-center items-center">
              {children}
            </main>
            <Footer />
          </div>
        </body>
      </html>
    </Providers>
  );
}
