import 'react-toastify/dist/ReactToastify.css'
import './globals.css'

import type { Metadata } from 'next'

import { Footer } from '@/components/Footer'
import Header from '@/components/Header'
import { Providers } from '@/lib/provider'
import { ToastContainer } from 'react-toastify'

export const metadata: Metadata = {
  title: 'Derm On Demand',
  description: 'Generated by Derma On Demand',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <Providers>
      <html lang="en">
        <body className="bg-[#EFF5F6]">
          <Header />
          <ToastContainer />
          {children}
          <Footer />
        </body>
      </html>
    </Providers>
  )
}
